### Aula 03
Introdução a aula 03
---
- Biblioteca Pandas
- Biblioteca Numpy
---
```python
print("Olá mundo")
```
1. Conhecendo a biblioteca
2. Executando comandos

In [1]:
import pandas as pd
import numpy as np

In [2]:
quantidade_produtos = [3,5,6,10]
preco_produtos = [10,5,7,100]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(preco_produtos)

faturamento = array_produtos * array_precos
print(faturamento)

[  30   25   42 1000]

In [3]:
quantidade_produtos = [3,5,6,10]
preco_produtos = [10,5,7,100]
nomes_produtos = ["Caçulinha","Pastel","Refrigerante","Combos"]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(preco_produtos)

faturamento = array_produtos * array_precos


for nome,preco in zip(nomes_produtos,faturamento):
    print(f"{nome} : {preco}")

Caçulinha : 30
Pastel : 25
Refrigerante : 42
Combos : 1000

#

### Exercício de fixação 
- Criar uma lista que irá possuir 10 nomes de produtos.
- Criar uma lista que irá possuir o preço de custo (atacado).
- Criar uma lista que irá possuir o preço de venda (varejo).
- Ao final, exibir o lucro obtido em cada produto.

In [4]:
#Lista de nomes
produtos = ["Celular","Televisão","Notebook","Computador","Teclado"]
#Lista de preços atacado
preco_atacado = [2000,3000,4500,5000,100]
#Lista de preços varejo
preco_varejo = [2500,4000,5000,7000,120]
#Array
array_atacado = np.array(preco_atacado)
array_varejo = np.array(preco_varejo)

lucro = array_varejo - array_atacado
lucro_obtido = np.sum(lucro)
print(f"O lucro obtido foi R${lucro_obtido}")

for nome,lucro_produto in zip(produtos,lucro):
    print(f"O lucro do produto {nome} foi {lucro_produto}")

O lucro obtido foi R$4020
O lucro do produto Celular foi 500
O lucro do produto Televisão foi 1000
O lucro do produto Notebook foi 500
O lucro do produto Computador foi 2000
O lucro do produto Teclado foi 20

# Pandas

In [5]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head() #Por padrão, ele exibe as 5 primeiras informações

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [6]:
df.tail() #Exibe as 5 últimas

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [7]:
#Dimensões da tabela
df.shape

(40, 6)

In [8]:
#Exibe as colunas da base de dados
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [10]:
#Contar valores duplicados
df.duplicated().sum()

np.int64(0)

In [11]:
#Contar valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [12]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [37]:
#Apelido pd
import pandas as pd 
import numpy as np

In [38]:
#Leitura dos dados
df = pd.read_csv(r"data\dataset_aula1_numpy_pandas.csv")

In [ ]:
#Exibindo a tabela
df

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0             1  Montagem          72.62          41.77           111      0
1             2  Usinagem          81.65          34.08           128      0
2             3  Usinagem          68.87          39.44           159      0
3             4  Usinagem          66.84          34.52            98      0
4             5  Usinagem          66.23          31.57            94      0
5             6  Usinagem          64.79          37.09            83      0
6             7  Usinagem          85.02          36.34           106      1
7             8  Inspeção          60.31          33.77           124      0
8             9  Montagem          75.84          29.65            92      0
9            10  Inspeção          68.38          28.93           145      1
10           11  Usinagem          76.31          35.48           149      0
11           12  Inspeção          74.79          33.37           134      0
12           13  Usinagem          76.31          36.51           154      0
13           14  Montagem          63.28          33.71           129      0
14           15  Montagem          64.98          33.24            83      0
15           16  Montagem          81.48          30.50           102      0
16           17  Montagem          79.62          39.68            85      1
17           18  Inspeção          69.80          27.20            91      0
18           19  Inspeção          77.16          47.45            99      0
19           20  Usinagem          73.30          39.77           119      1
20           21  Inspeção          79.77          38.04            91      0
21           22  Usinagem          71.76          35.16            80      0
22           23  Inspeção          74.16          31.93           149      0
23           24  Usinagem          74.69          32.34           123      1
24           25  Usinagem          74.03          32.71           145      1
25           26  Usinagem          75.96          38.70            93      0
26           27  Usinagem          60.80          37.18           159      0
27           28  Montagem          69.37          35.90           122      1
28           29  Montagem          70.28          35.04           103      0
29           30  Inspeção          73.53          32.84            82      0
30           31  Montagem          63.59          42.29           159      1
31           32  Inspeção          68.91          32.66           155      0
32           33  Inspeção          77.62          35.70           108      1
33           34  Inspeção          73.32          32.18           129      1
34           35  Usinagem          78.24          31.93           158      0
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [ ]:
#Exibe o corpo da base
df.shape

(40, 6)

In [ ]:
#Exibe as colunas
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [43]:
#Procura por valores nulos e o sum() realiza a contagem
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [45]:
df.notnull().sum() #Procura por valores não nulos, e o sum() realiza a contagem.

id_registro      40
setor            40
temperatura_c    40
tempo_ciclo_s    40
producao_dia     40
falha            40
dtype: int64

In [46]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [47]:
#Registros de temperatura
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [ ]:
#Combinando filtros
df[["temperatura_c","id_registro"]]1

    temperatura_c  id_registro
0           72.62            1
1           81.65            2
2           68.87            3
3           66.84            4
4           66.23            5
5           64.79            6
6           85.02            7
7           60.31            8
8           75.84            9
9           68.38           10
10          76.31           11
11          74.79           12
12          76.31           13
13          63.28           14
14          64.98           15
15          81.48           16
16          79.62           17
17          69.80           18
18          77.16           19
19          73.30           20
20          79.77           21
21          71.76           22
22          74.16           23
23          74.69           24
24          74.03           25
25          75.96           26
26          60.80           27
27          69.37           28
28          70.28           29
29          73.53           30
30          63.59           31
31          68.91           32
32          77.62           33
33          73.32           34
34          78.24           35
35          68.47           36
36          75.62           37
37          78.50           38
38          76.19           39
39          68.64           40

In [56]:
df["classificacao_temperatura"] = np.where(df["temperatura_c"] >= 75,"Alta","Baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,Baixa
1,2,Usinagem,81.65,34.08,128,0,Alta
2,3,Usinagem,68.87,39.44,159,0,Baixa
3,4,Usinagem,66.84,34.52,98,0,Baixa
4,5,Usinagem,66.23,31.57,94,0,Baixa